# Docker compose file for netprobe
# https://github.com/plaintextpackets/netprobe_lite
name: netprobe

networks:
  netprobe-net:
  proxy:
    external: true   

services:
  redis:
    restart: always
    container_name: netprobe-redis
    image: "redis:latest"
    volumes:
      - ./config/redis:/etc/redis/
    networks:
      - netprobe-net
        
  netprobe:
    restart: always
    container_name: netprobe-probe
    image: "plaintextpackets/netprobe:latest"
    volumes:
      - ./:/netprobe_lite
    environment:
      MODULE: "NETPROBE"
    networks:
      - netprobe-net

  presentation:
    restart: always
    container_name: netprobe-presentation
    image: "plaintextpackets/netprobe:latest"
    volumes:
      - ./:/netprobe_lite
    environment:
      MODULE: "PRESENTATION"
    networks:
      - netprobe-net

  prometheus:
    restart: always
    container_name: netprobe-prometheus
    image: "prom/prometheus"
    volumes:
      - ./config/prometheus:/etc/prometheus/
      - prometheus_data:/prometheus  # Persistent local storage for Prometheus data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - netprobe-net

  grafana:
    restart: always
    container_name: netprobe-grafana
    image: grafana/grafana-enterprise
    volumes:
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./config/grafana/dashboards/main:/etc/grafana/provisioning/dashboards/
      - ./config/grafana/dashboards/json:/var/lib/grafana/dashboards/
      - grafana_data:/var/lib/grafana
        #    ports:
        #      - '3001:3000'
    networks:
      - proxy
      - netprobe-net
    labels:
      - "traefik.enable=true"

        ## Public Insecure
      - "traefik.http.routers.grafana.entrypoints=http-public"
      - "traefik.http.routers.grafana.rule=Host(`grafana-prod.hirschykiss.net`)"
      - "traefik.http.middlewares.grafana-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.grafana.middlewares=grafana-https-redirect"

        ## Public Secure
      - "traefik.http.routers.grafana-secure.entrypoints=https-public"
      - "traefik.http.routers.grafana-secure.rule=Host(`grafana-prod.hirschykiss.net`)"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.tls.domains[0].main=hirschykiss.net"
      - "traefik.http.routers.grafana-secure.tls.domains[0].sans=*.hirschykiss.net"
      - "traefik.http.routers.grafana-secure.tls.certresolver=production"
      - "traefik.http.routers.grafana-secure.service=grafana-secure"
      - "traefik.http.services.grafana-secure.loadbalancer.server.port=3000"

        ## Private Insecure
      - "traefik.http.routers.grafana-private.entrypoints=http"
      - "traefik.http.routers.grafana-private.rule=Host(`grafana-prod.home.hirschykiss.net`)"
      - "traefik.http.middlewares.grafana-private-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.grafana-private.middlewares=grafana-private-https-redirect"

        ## Private Secure
      - "traefik.http.routers.grafana-private-secure.entrypoints=https"
      - "traefik.http.routers.grafana-private-secure.rule=Host(`grafana-prod.home.hirschykiss.net`)"
      - "traefik.http.routers.grafana-private-secure.tls=true"
      - "traefik.http.routers.grafana-private-secure.service=grafana-private-secure"
      - "traefik.http.services.grafana-private-secure.loadbalancer.server.port=3000"

      - "traefik.docker.network=proxy"

  prometheus-pve-exporter:
    restart: always
    container_name: prometheus-pve-exporter
    image: prompve/prometheus-pve-exporter
      #ports:
      #- "9221:9221"
    volumes:
      - ./config/pve:/etc/prometheus/
    networks:
      - netprobe-net     

  pihole:
    container_name: pihole
    restart: always
    image: ekofr/pihole-exporter:latest
    environment:
      - PIHOLE_HOSTNAME=10.10.0.11
      - PIHOLE_API_TOKEN=5871477110c0452f928714ef19e0d732ff9c0b6f3c7826f445f9c4039636fdb9
      - PORT=9617
        #ports:
        # - "9617:9617"
    networks:
      - netprobe-net

  unpoller:
    image: ghcr.io/unpoller/unpoller:latest
    restart: unless-stopped
      #ports:
      # - '9130:9130'
    container_name: unpoller
    networks:
      - netprobe-net
    environment:
      - UP_INFLUXDB_DISABLE=true
      - UP_POLLER_DEBUG=false
      - UP_UNIFI_DYNAMIC=false
      - UP_PROMETHEUS_HTTP_LISTEN=0.0.0.0:9130
      - UP_PROMETHEUS_NAMESPACE=unpoller
      - UP_UNIFI_CONTROLLER_0_USER=${UNIFI_USER}
      - UP_UNIFI_CONTROLLER_0_PASS=${UNIFI_PASS}
      - UP_UNIFI_CONTROLLER_0_SAVE_ALARMS=true
      - UP_UNIFI_CONTROLLER_0_SAVE_ANOMALIES=true
      - UP_UNIFI_CONTROLLER_0_SAVE_DPI=true
      - UP_UNIFI_CONTROLLER_0_SAVE_EVENTS=true
      - UP_UNIFI_CONTROLLER_0_SAVE_IDS=true
      - UP_UNIFI_CONTROLLER_0_SAVE_SITES=true
      - UP_UNIFI_CONTROLLER_0_URL=https://10.10.0.1:443

  truenas_exporter:
    image: prom/graphite-exporter:latest
    container_name: truenas_exporter
    restart: unless-stopped
    networks:
      - netprobe-net
    ports:
      #    - '9108:9108'
    - '2003:9109'
    volumes:
      - ./config/graphite/graphite_mappings.yaml:/tmp/graphite_mapping.yaml
    command: ["--graphite.mapping-config=/tmp/graphite_mapping.yaml"]
volumes:
  prometheus_data:
  grafana_data:

