# Docker compose file for netprobe
# https://github.com/plaintextpackets/netprobe_lite
name: netprobe

networks:
  netprobe-net:
    
services:
  redis:
    restart: always
    container_name: netprobe-redis
    image: "redis:latest"
    volumes:
      - ./config/redis/redis.conf:/etc/redis/redis.conf
    networks:
      - netprobe-net
        
  netprobe:
    restart: always
    container_name: netprobe-probe
    image: "plaintextpackets/netprobe:latest"
    volumes:
      - .:/netprobe_lite
    environment:
      MODULE: "NETPROBE"
    networks:
      - netprobe-net

  presentation:
    restart: always
    container_name: netprobe-presentation
    image: "plaintextpackets/netprobe:latest"
    volumes:
      - .:/netprobe_lite
    environment:
      MODULE: "PRESENTATION"
    networks:
      - netprobe-net

  prometheus:
    restart: always
    container_name: netprobe-prometheus
    image: "prom/prometheus"
    volumes:
      - ./config/prometheus:/etc/prometheus/
      - prometheus_data:/prometheus  # Persistent local storage for Prometheus data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - netprobe-net

  grafana:
    restart: always
    container_name: netprobe-grafana
    image: grafana/grafana-enterprise
    volumes:
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./config/grafana/dashboards/main:/etc/grafana/provisioning/dashboards/
      - ./config/grafana/dashboards/json:/var/lib/grafana/dashboards/
        #      - ./config/grafana/dashboards/plex.json:/var/lib/grafana/dashboards/plex.json
        #      - ./config/grafana/dashboards/truenas.json:/var/lib/grafana/dashboards/truenas.json
      - grafana_data:/var/lib/grafana
    ports:
      - '3001:3000'
    networks:
      - netprobe-net

  prometheus-pve-exporter:
    restart: always
    container_name: prometheus-pve-exporter
    image: prompve/prometheus-pve-exporter
      #ports:
      #- "9221:9221"
    volumes:
      - ./config/prometheus/pve.yml:/etc/prometheus/pve.yml
    networks:
      - netprobe-net     

  pihole:
    image: ekofr/pihole-exporter:latest
    environment:
      - PIHOLE_HOSTNAME=10.10.0.11
      - PIHOLE_API_TOKEN=5871477110c0452f928714ef19e0d732ff9c0b6f3c7826f445f9c4039636fdb9
      - PORT=9617
        #ports:
        # - "9617:9617"
    networks:
      - netprobe-net

  unpoller:
    image: ghcr.io/unpoller/unpoller:latest
    restart: unless-stopped
      #ports:
      # - '9130:9130'
    container_name: unpoller
    networks:
      - netprobe-net
    environment:
      - UP_INFLUXDB_DISABLE=true
      - UP_POLLER_DEBUG=false
      - UP_UNIFI_DYNAMIC=false
      - UP_PROMETHEUS_HTTP_LISTEN=0.0.0.0:9130
      - UP_PROMETHEUS_NAMESPACE=unpoller
      - UP_UNIFI_CONTROLLER_0_USER=${UNIFI_USER}
      - UP_UNIFI_CONTROLLER_0_PASS=${UNIFI_PASS}
      - UP_UNIFI_CONTROLLER_0_SAVE_ALARMS=true
      - UP_UNIFI_CONTROLLER_0_SAVE_ANOMALIES=true
      - UP_UNIFI_CONTROLLER_0_SAVE_DPI=true
      - UP_UNIFI_CONTROLLER_0_SAVE_EVENTS=true
      - UP_UNIFI_CONTROLLER_0_SAVE_IDS=true
      - UP_UNIFI_CONTROLLER_0_SAVE_SITES=true
      - UP_UNIFI_CONTROLLER_0_URL=https://10.10.0.1:443

volumes:
  prometheus_data:
  grafana_data:

