{
 "title": "Plex",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "plex_info == 1", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Heartbeat",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "plex_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Health",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "plex_up", "legendFormat": "Heartbeat" }
   ]
  },
  {
   "title": "Streams",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(plex_sessions_count{state!=\"paused\"})"
    }
   ]
  },
  {
   "title": "Transcodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(plex_video_transcode_sessions_count{state!=\"paused\"})"
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(plex_media_downloads_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily Library Movements",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "delta(plex_media_count[1d] offset 1d)",
     "legendFormat": "{{ title }}"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(plex_video_transcode_sessions_count{state!=\"paused\"})",
     "legendFormat": "Transcodes"
    },
    {
     "expr": "sum(plex_sessions_count{state!=\"paused\"})",
     "legendFormat": "Streams"
    },
    {
     "expr": "sum(plex_media_downloads_count) > 0",
     "legendFormat": "Downloads"
    }
   ]
  },
  {
   "title": "Library",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "plex_media_count", "legendFormat": "{{ title }}" }
   ]
  },
  {
   "title": "Download Durations",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum_over_time(plex_media_downloads_count[$__range]) > 0)",
     "legendFormat": "{{ username }}"
    }
   ]
  }
 ]
}