acl internal {

	10.0.0.0/8;
	172.16.0.0/12;
	192.168.0.0/16;
};

options {
	forwarders {
		10.10.10.54;
	};
	allow-query { internal; };
};
zone "home.hirschykiss.net" IN {
	type master;
	file "/etc/bind/hirschykiss-net.zone";
};
