{
 "title": "TrueNAS",
 "tags": [
  "TrueNAS",
  "Prometheus",
  "Broken"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "hostname", "query": { "query": "truenas_uptime_uptime" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "truenas_uptime_uptime{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Disk Temperature (°C)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truenas_disktemp_temperature{hostname=\"$hostname\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Dataset Space Free",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truenas_dataset_df_complex_free{hostname=\"$hostname\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "bargauge",
   "description": "Subtracts the weird idle from 100 which comes out to the total used.",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - truenas_aggregation_cpu_cpu_idle{hostname=\"$hostname\", device=\"average\"}",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "truenas_load_longterm{hostname=\"$hostname\"}",
     "legendFormat": "logterm"
    },
    { "expr": "truenas_load_midterm", "legendFormat": "midterm" },
    { "expr": "truenas_load_shortterm", "legendFormat": "shortterm" }
   ]
  },
  {
   "title": "Swap Utilization",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "truenas_swap_swap_used{hostname=\"$hostname\"}",
     "legendFormat": "used"
    },
    {
     "expr": "truenas_swap_swap_free{hostname=\"$hostname\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Physical Memory Utilization",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truenas_memory_buffered{hostname=\"$hostname\"}",
     "legendFormat": "buffered"
    },
    {
     "expr": "truenas_memory_cached{hostname=\"$hostname\"}",
     "legendFormat": "cached"
    },
    {},
    {
     "expr": "truenas_memory_free{hostname=\"$hostname\"}",
     "legendFormat": "free"
    },
    {
     "expr": "truenas_memory_slab_recl{hostname=\"$hostname\"}",
     "legendFormat": "slab_recl"
    },
    {
     "expr": "truenas_memory_slab_unrecl{hostname=\"$hostname\"}",
     "legendFormat": "slab_unrecl"
    },
    {
     "expr": "truenas_memory_used{hostname=\"$hostname\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Disk I/O time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "truenas_disk_io_time_io_time{hostname=\"$hostname\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "truenas_disktemp_temperature{hostname=\"$hostname\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Interface Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "truenas_interface_packets_rx{hostname=\"$hostname\"}",
     "legendFormat": "{{device}} in"
    },
    {
     "expr": "truenas_interface_packets_tx{hostname=\"$hostname\"}",
     "legendFormat": "{{device}} out"
    }
   ]
  },
  {
   "title": "NFS Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 22 },
   "targets": [
    {
     "expr": "truenas_nfsstat_nfsstat_nfsv3_op_read{hostname=\"$hostname\"}",
     "legendFormat": "v3 read"
    },
    {
     "expr": "truenas_nfsstat_nfsstat_nfsv3_op_write{hostname=\"$hostname\"}",
     "legendFormat": "v3 write"
    },
    {
     "expr": "truenas_nfsstat_nfsstat_nfsv4_op_read{hostname=\"$hostname\"}",
     "legendFormat": "v4 read"
    },
    {
     "expr": "truenas_nfsstat_nfsstat_nfsv4_op_write{hostname=\"$hostname\"}",
     "legendFormat": "v4 write"
    }
   ]
  },
  {
   "title": "ARC Size",
   "type": "timeseries",
   "description": "Automatic Reference Counting Size",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "truenas_zfs_arc_cache_size_arc{hostname=\"$hostname\"}",
     "legendFormat": "ARC"
    },
    {
     "expr": "truenas_zfs_arc_cache_size_L2{hostname=\"$hostname\"}",
     "legendFormat": "L2"
    }
   ]
  },
  {
   "title": "ARC Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 30 },
   "targets": [
    {
     "expr": "truenas_zfs_arc_cache_ratio_arc{hostname=\"$hostname\"} * 100",
     "legendFormat": "ARC"
    },
    {
     "expr": "truenas_zfs_arc_cache_ratio_L2{hostname=\"$hostname\"} * 100",
     "legendFormat": "L2"
    }
   ]
  }
 ]
}