{
 "title": "Uptime Kuma",
 "description": "A dashboard to visualize the metrics from HTTP endpoints in [Uptime Kuma](https://github.com/louislam/uptime-kuma)",
 "tags": [
  "uptime-kuma",
  "Homelab Service"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "type",
    "query": {
     "query": "label_values(monitor_response_time, monitor_type)"
    }
   },
   {
    "name": "monitor",
    "query": {
     "query": "label_values(monitor_response_time{monitor_type=~\"$type\"}, monitor_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Monitors",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(monitor_status{monitor_type=~\"$type\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Online Monitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(monitor_status{monitor_type=~\"$type\"} == 1) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Offline Monitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(monitor_status{monitor_type=~\"$type\"} == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time (2h)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(monitor_response_time[2h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "monitor",
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "monitor_status{monitor_name=~\"$monitor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 15, "x": 3, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "monitor_response_time{monitor_name=~\"$monitor\"}",
       "legendFormat": "Current"
      },
      {
       "expr": "avg_over_time(monitor_response_time{monitor_name=~\"$monitor\"}[24h])",
       "legendFormat": "AVG 24H"
      }
     ]
    },
    {
     "title": "Certificate days until expire",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 18, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "monitor_cert_days_remaining{monitor_name=~\"$monitor\"}",
       "legendFormat": "Current"
      }
     ]
    },
    {
     "title": "Certificate Valid",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 21, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "monitor_cert_is_valid{monitor_name=~\"$monitor\"}",
       "legendFormat": "Current"
      }
     ]
    }
   ]
  }
 ]
}